import { Vehicle } from '../models/Vehicle.js';

export function getSeedVehicles(locationsMap) {
  const getLoc = (city) => locationsMap[city.toLowerCase()] || locationsMap['bhilai'];

  return [
    // ==========================================
    // 🚗 CARS (HATCHBACKS & SEDANS)
    // ==========================================
    {
      brand: 'Maruti Suzuki',
      model: 'Swift',
      variant: 'ZXi+ Dual Tone',
      type: 'car',
      category: 'Hatchback',
      seatingCapacity: 5,
      doors: 5,
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'Front-Wheel Drive',
      engine: { displacementCC: 1197, powerBHP: 89, torqueNm: 113 },
      rental: { pricePerHour: 120, pricePerDay: 1800, pricePerWeek: 11000, refundableDeposit: 4000 },
      location: getLoc('Bhilai')._id,
      cityName: 'Bhilai',
      availableCities: ['Bhilai', 'Raipur', 'Durg', 'Nagpur'],
      coordinates: { type: 'Point', coordinates: [81.3629, 21.2121] },
      specifications: { acceleration: '0-100 in 11.2s', topSpeed: '165 km/h', mileage: '22.4 km/l', luggageCapacity: '268 Litres', fuelTankCapacity: '37 Litres' },
      features: ['SmartPlay Pro+ 9" Touchscreen', 'Cruise Control', 'Auto Climate Control', 'Push Start/Stop', 'Reverse Parking Camera', 'LED Projector Headlamps'],
      images: [{ url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1000&q=80', alt: 'Maruti Swift' }],
      colorOptions: [{ name: 'Sizzling Red with Midnight Black', hex: '#b31b1b' }, { name: 'Pearl Arctic White', hex: '#f0f2f5' }, { name: 'Magma Grey', hex: '#484c52' }],
      description: 'The definitive peppy city hatchback. Agile handling, class-leading fuel economy, and effortless city navigation across Chhattisgarh.',
      rating: 4.7,
      reviewsCount: 142,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Hyundai',
      model: 'i20',
      variant: 'Asta (O) 1.2 IVT',
      type: 'car',
      category: 'Hatchback',
      seatingCapacity: 5,
      doors: 5,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      drivetrain: 'Front-Wheel Drive',
      engine: { displacementCC: 1197, powerBHP: 87, torqueNm: 115 },
      rental: { pricePerHour: 140, pricePerDay: 2200, pricePerWeek: 13500, refundableDeposit: 5000 },
      location: getLoc('Raipur')._id,
      cityName: 'Raipur',
      availableCities: ['Raipur', 'Bhilai', 'Durg'],
      coordinates: { type: 'Point', coordinates: [81.6296, 21.2514] },
      specifications: { acceleration: '0-100 in 12.0s', topSpeed: '170 km/h', mileage: '19.6 km/l', luggageCapacity: '311 Litres', fuelTankCapacity: '37 Litres' },
      features: ['10.25" HD Touchscreen', 'Bose 7-Speaker Sound System', 'Electric Sunroof', 'Wireless Charging', 'BlueLink Connected Tech'],
      images: [{ url: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1000&q=80', alt: 'Hyundai i20' }],
      colorOptions: [{ name: 'Fiery Red', hex: '#9c1414' }, { name: 'Polar White', hex: '#ffffff' }, { name: 'Starry Night', hex: '#0f1a30' }],
      description: 'Premium European-inspired hatchback loaded with tech, plush cockpit comfort, and seamless automatic transmission.',
      rating: 4.8,
      reviewsCount: 96,
      isFeatured: false,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Honda',
      model: 'City',
      variant: 'ZX 1.5 i-VTEC CVT',
      type: 'car',
      category: 'Sedan',
      seatingCapacity: 5,
      doors: 4,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      drivetrain: 'Front-Wheel Drive',
      engine: { displacementCC: 1498, powerBHP: 119, torqueNm: 145 },
      rental: { pricePerHour: 190, pricePerDay: 3200, pricePerWeek: 19500, refundableDeposit: 6000 },
      location: getLoc('Nagpur')._id,
      cityName: 'Nagpur',
      availableCities: ['Nagpur', 'Raipur', 'Mumbai', 'Pune'],
      coordinates: { type: 'Point', coordinates: [79.0882, 21.1458] },
      specifications: { acceleration: '0-100 in 10.1s', topSpeed: '195 km/h', mileage: '18.4 km/l', luggageCapacity: '506 Litres', fuelTankCapacity: '40 Litres' },
      features: ['Honda SENSING ADAS Suite', 'Electric One-Touch Sunroof', 'LaneWatch Camera', 'Plush Leatherette Seats', 'Full LED Matrix Headlamps'],
      images: [{ url: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1000&q=80', alt: 'Honda City' }],
      colorOptions: [{ name: 'Golden Brown Metallic', hex: '#443224' }, { name: 'Platinum White Pearl', hex: '#f7f7f7' }, { name: 'Radiant Red Metallic', hex: '#871a1a' }],
      description: 'The executive benchmark sedan in India. Supreme rear legroom, serene highway ride, and legendary i-VTEC performance.',
      rating: 4.9,
      reviewsCount: 128,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Hyundai',
      model: 'Verna',
      variant: 'SX (O) 1.5 Turbo DCT',
      type: 'car',
      category: 'Sedan',
      seatingCapacity: 5,
      doors: 4,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      drivetrain: 'Front-Wheel Drive',
      engine: { displacementCC: 1482, powerBHP: 158, torqueNm: 253 },
      rental: { pricePerHour: 220, pricePerDay: 3600, pricePerWeek: 22000, refundableDeposit: 7000 },
      location: getLoc('Delhi')._id,
      cityName: 'Delhi',
      availableCities: ['Delhi', 'Mumbai', 'Bengaluru', 'Bhilai'],
      coordinates: { type: 'Point', coordinates: [77.2167, 28.6328] },
      specifications: { acceleration: '0-100 in 8.1s', topSpeed: '210 km/h', mileage: '20.6 km/l', luggageCapacity: '528 Litres', fuelTankCapacity: '45 Litres' },
      features: ['Level 2 ADAS (17 Features)', 'Dual 10.25" Curved Screens', 'Ventilated & Heated Front Seats', '64-Color Ambient Lights', 'Bose 8-Speaker Sound'],
      images: [{ url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1000&q=80', alt: 'Hyundai Verna Turbo' }],
      colorOptions: [{ name: 'Abyss Black', hex: '#0c0d0e' }, { name: 'Atlas White', hex: '#ffffff' }, { name: 'Tellurian Brown', hex: '#483c32' }],
      description: 'Futuristic fastback styling powered by a beastly 160PS Turbo engine with lightning-quick 7-speed DCT gearshifts.',
      rating: 4.9,
      reviewsCount: 77,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },

    // ==========================================
    // 🚙 SUVS & 4X4 ADVENTURE
    // ==========================================
    {
      brand: 'Mahindra',
      model: 'Thar',
      variant: 'LX Hard Top 4x4 Diesel AT',
      type: 'car',
      category: 'SUV',
      seatingCapacity: 4,
      doors: 3,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: 'Four-Wheel Drive (4x4 with Low-Range)',
      engine: { displacementCC: 2184, powerBHP: 130, torqueNm: 300 },
      rental: { pricePerHour: 280, pricePerDay: 4500, pricePerWeek: 28000, refundableDeposit: 10000 },
      location: getLoc('Bhilai')._id,
      cityName: 'Bhilai',
      availableCities: ['Bhilai', 'Raipur', 'Durg', 'Nagpur', 'Goa'],
      coordinates: { type: 'Point', coordinates: [81.3629, 21.2121] },
      specifications: { acceleration: '0-100 in 11.8s', topSpeed: '155 km/h', mileage: '15.2 km/l', luggageCapacity: '250 Litres', fuelTankCapacity: '57 Litres' },
      features: ['Shift-on-the-Fly 4x4 Manual Transfer Case', 'Mechanical Locking Differential', 'Roll-over Mitigation', 'Washable Interior with Drain Plugs', '7" Water-Resistant Touchscreen'],
      images: [{ url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=80', alt: 'Mahindra Thar 4x4' }],
      colorOptions: [{ name: 'Napoli Black', hex: '#0f1011' }, { name: 'Red Rage', hex: '#ab1818' }, { name: 'Galaxy Grey', hex: '#3b3e42' }],
      description: 'The ultimate Indian off-road icon. Built to conquer rugged terrains, river crossings, jungle trails, and Chhattisgarh highways.',
      rating: 4.9,
      reviewsCount: 210,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Mahindra',
      model: 'Thar ROXX',
      variant: 'AX7 L 4x4 5-Door Panoramic',
      type: 'car',
      category: 'SUV',
      seatingCapacity: 5,
      doors: 5,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: 'Four-Wheel Drive (4x4 with 4XPLOR Modes)',
      engine: { displacementCC: 2184, powerBHP: 172, torqueNm: 370 },
      rental: { pricePerHour: 340, pricePerDay: 5500, pricePerWeek: 34000, refundableDeposit: 12000 },
      location: getLoc('Raipur')._id,
      cityName: 'Raipur',
      availableCities: ['Raipur', 'Bhilai', 'Delhi', 'Mumbai', 'Bengaluru'],
      coordinates: { type: 'Point', coordinates: [81.6296, 21.2514] },
      specifications: { acceleration: '0-100 in 10.2s', topSpeed: '170 km/h', mileage: '14.8 km/l', luggageCapacity: '644 Litres', fuelTankCapacity: '57 Litres' },
      features: ['Panoramic Skyroof', 'Harman Kardon 9-Speaker Audio', 'Level 2 ADAS Suite', 'Ventilated Leatherette Seats', '10.25" HD Twin Digital Screens'],
      images: [{ url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80', alt: 'Mahindra Thar ROXX 5-Door' }],
      colorOptions: [{ name: 'Stealth Black', hex: '#0a0a0c' }, { name: 'Deep Forest', hex: '#16281b' }, { name: 'Everest White', hex: '#f2f2f4' }],
      description: 'The all-new 5-door Thar ROXX. World-class luxury meets hardcore 4x4 capabilities with a massive panoramic sunroof and 644L boot.',
      rating: 5.0,
      reviewsCount: 64,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Hyundai',
      model: 'Creta',
      variant: 'SX (O) 1.5 Turbo DCT',
      type: 'car',
      category: 'SUV',
      seatingCapacity: 5,
      doors: 5,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      drivetrain: 'Front-Wheel Drive',
      engine: { displacementCC: 1482, powerBHP: 158, torqueNm: 253 },
      rental: { pricePerHour: 240, pricePerDay: 3800, pricePerWeek: 24000, refundableDeposit: 8000 },
      location: getLoc('Bhilai')._id,
      cityName: 'Bhilai',
      availableCities: ['Bhilai', 'Raipur', 'Durg', 'Nagpur', 'Pune'],
      coordinates: { type: 'Point', coordinates: [81.3629, 21.2121] },
      specifications: { acceleration: '0-100 in 8.9s', topSpeed: '190 km/h', mileage: '18.4 km/l', luggageCapacity: '433 Litres', fuelTankCapacity: '50 Litres' },
      features: ['Panoramic Sunroof', 'Dual 10.25" Infotainment & Cockpit', '360-Degree Surround Camera', 'Bose Premium Audio System', 'Dual-Zone Climate Control'],
      images: [{ url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=80', alt: 'Hyundai Creta' }],
      colorOptions: [{ name: 'Robust Emerald Pearl', hex: '#0f2f24' }, { name: 'Abyss Black Pearl', hex: '#0c0d10' }, { name: 'Titan Grey', hex: '#484b50' }],
      description: "India's undisputable king of mid-size SUVs. Premium road presence, plush interiors, panoramic glass roof, and effortless turbo drive.",
      rating: 4.9,
      reviewsCount: 188,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Mahindra',
      model: 'Scorpio-N',
      variant: 'Z8 L 4x4 Diesel AT',
      type: 'car',
      category: 'SUV',
      seatingCapacity: 7,
      doors: 5,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: 'Four-Wheel Drive (4XPLOR Intelligent Terrain)',
      engine: { displacementCC: 2184, powerBHP: 172, torqueNm: 400 },
      rental: { pricePerHour: 300, pricePerDay: 4800, pricePerWeek: 30000, refundableDeposit: 10000 },
      location: getLoc('Raipur')._id,
      cityName: 'Raipur',
      availableCities: ['Raipur', 'Bhilai', 'Nagpur', 'Mumbai', 'Indore'],
      coordinates: { type: 'Point', coordinates: [81.6296, 21.2514] },
      specifications: { acceleration: '0-100 in 9.8s', topSpeed: '175 km/h', mileage: '14.0 km/l', luggageCapacity: '460 Litres', fuelTankCapacity: '57 Litres' },
      features: ['Sony 12-Speaker Immersive Audio 3D', '4XPLOR Intelligent Terrain Management', 'Electric Sunroof', 'Dual-Zone Fatiguels Auto AC', 'Captain Seats (6/7 Seater)'],
      images: [{ url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1000&q=80', alt: 'Mahindra Scorpio-N' }],
      colorOptions: [{ name: 'Deep Forest', hex: '#152419' }, { name: 'Napoli Black', hex: '#090a0c' }, { name: 'Dazzling Silver', hex: '#c5c8cc' }],
      description: 'The Big Daddy of SUVs. Imposing butch stance, 400Nm torque, supreme 7-seater space, and cutting-edge 4XPLOR terrain mastery.',
      rating: 4.9,
      reviewsCount: 154,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Mahindra',
      model: 'XUV700',
      variant: 'AX7 Luxury AWD Diesel AT',
      type: 'car',
      category: 'SUV',
      seatingCapacity: 7,
      doors: 5,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: 'All-Wheel Drive (AWD)',
      engine: { displacementCC: 2184, powerBHP: 182, torqueNm: 450 },
      rental: { pricePerHour: 320, pricePerDay: 5200, pricePerWeek: 32000, refundableDeposit: 10000 },
      location: getLoc('Mumbai')._id,
      cityName: 'Mumbai',
      availableCities: ['Mumbai', 'Pune', 'Bengaluru', 'Delhi', 'Raipur'],
      coordinates: { type: 'Point', coordinates: [72.8697, 19.0657] },
      specifications: { acceleration: '0-100 in 9.3s', topSpeed: '190 km/h', mileage: '15.5 km/l', luggageCapacity: '480 Litres', fuelTankCapacity: '60 Litres' },
      features: ['Skyroof (Largest in Segment)', 'Level 2 ADAS with Adaptive Cruise', 'Sony 3D Sound 12 Speakers', 'Dual 10.25" Superscreens', 'Wireless Apple CarPlay'],
      images: [{ url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=1000&q=80', alt: 'Mahindra XUV700' }],
      colorOptions: [{ name: 'Midnight Black', hex: '#0d1117' }, { name: 'Electric Blue', hex: '#0055b3' }, { name: 'Dazzling Silver', hex: '#d6d9dc' }],
      description: 'The technology flagship of Indian motoring. High-speed highway stability, 450Nm pulling power, and segment-leading safety.',
      rating: 4.9,
      reviewsCount: 167,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Tata',
      model: 'Safari',
      variant: 'Accomplished+ Dark Edition AT',
      type: 'car',
      category: 'SUV',
      seatingCapacity: 7,
      doors: 5,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: 'Front-Wheel Drive',
      engine: { displacementCC: 1956, powerBHP: 168, torqueNm: 350 },
      rental: { pricePerHour: 310, pricePerDay: 5000, pricePerWeek: 31000, refundableDeposit: 10000 },
      location: getLoc('Bengaluru')._id,
      cityName: 'Bengaluru',
      availableCities: ['Bengaluru', 'Hyderabad', 'Pune', 'Mumbai'],
      coordinates: { type: 'Point', coordinates: [77.6412, 12.9784] },
      specifications: { acceleration: '0-100 in 10.4s', topSpeed: '180 km/h', mileage: '16.1 km/l', luggageCapacity: '420 Litres', fuelTankCapacity: '50 Litres' },
      features: ['12.3" Cinematic Touchscreen', 'Ventilated 1st & 2nd Row Seats', 'JBL 10-Speaker Audio with Subwoofer', 'Voice-Assisted Panoramic Sunroof', 'Gesture-Controlled Power Tailgate'],
      images: [{ url: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1000&q=80', alt: 'Tata Safari Dark Edition' }],
      colorOptions: [{ name: 'Oberon Black Dark Edition', hex: '#050608' }, { name: 'Stardust Ash', hex: '#404347' }],
      description: 'Five-star Global NCAP safety champion. Ultra-luxurious 3-row comfort, signature dark-mode styling, and Land Rover-derived D8 platform dynamics.',
      rating: 4.8,
      reviewsCount: 82,
      isFeatured: false,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Toyota',
      model: 'Fortuner',
      variant: 'Legender 4x4 Diesel AT',
      type: 'car',
      category: 'SUV',
      seatingCapacity: 7,
      doors: 5,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: 'Four-Wheel Drive (4x4 with High/Low Range)',
      engine: { displacementCC: 2755, powerBHP: 201, torqueNm: 500 },
      rental: { pricePerHour: 450, pricePerDay: 7500, pricePerWeek: 48000, refundableDeposit: 15000 },
      location: getLoc('Delhi')._id,
      cityName: 'Delhi',
      availableCities: ['Delhi', 'Mumbai', 'Raipur', 'Bengaluru', 'Goa'],
      coordinates: { type: 'Point', coordinates: [77.2167, 28.6328] },
      specifications: { acceleration: '0-100 in 9.6s', topSpeed: '185 km/h', mileage: '12.8 km/l', luggageCapacity: '500 Litres', fuelTankCapacity: '80 Litres' },
      features: ['500 Nm Massive Torque', '11-Speaker JBL Audio', 'Sequential LED Indicators', 'Wireless Charger & Kick Tailgate', 'Unbreakable Ladder Frame Chassis'],
      images: [{ url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1000&q=80', alt: 'Toyota Fortuner Legender' }],
      colorOptions: [{ name: 'White Pearl Crystal Shine & Black Roof', hex: '#f4f5f8' }, { name: 'Attitude Black', hex: '#0a0a0c' }],
      description: 'The supreme symbol of power and unmatched bulletproof reliability on Indian roads. 500Nm torque and legendary VIP road presence.',
      rating: 4.9,
      reviewsCount: 230,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },

    // ==========================================
    // 👑 ULTRA-LUXURY & SPORTS CARS
    // ==========================================
    {
      brand: 'BMW',
      model: 'X5',
      variant: 'xDrive40i M Sport',
      type: 'car',
      category: 'Luxury',
      seatingCapacity: 5,
      doors: 5,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      drivetrain: 'All-Wheel Drive (xDrive)',
      engine: { displacementCC: 2998, powerBHP: 375, torqueNm: 520 },
      rental: { pricePerHour: 650, pricePerDay: 9800, pricePerWeek: 60000, refundableDeposit: 20000 },
      location: getLoc('Bhilai')._id,
      cityName: 'Bhilai',
      availableCities: ['Bhilai', 'Raipur', 'Delhi', 'Mumbai', 'Bengaluru'],
      coordinates: { type: 'Point', coordinates: [81.3629, 21.2121] },
      specifications: { acceleration: '0-100 in 5.3s', topSpeed: '250 km/h', mileage: '11.2 km/l', luggageCapacity: '650 Litres', fuelTankCapacity: '83 Litres' },
      features: ['TwinPower Turbo Inline-6 Engine', 'Sky Lounge Panoramic Glass Roof', 'Harman Kardon Surround Sound', '360° Parking Assistant Plus', 'Adaptive 2-Axle Air Suspension'],
      images: [{ url: 'https://images.unsplash.com/photo-1555353540-64580b51c258?auto=format&fit=crop&w=1000&q=80', alt: 'BMW X5 xDrive40i' }],
      colorOptions: [{ name: 'Carbon Black Metallic', hex: '#08090b' }, { name: 'Mineral White', hex: '#f7f8fa' }, { name: 'Phytonic Blue', hex: '#102a5c' }],
      description: 'The pinnacle of German luxury sports utility. TwinPower Turbo inline-6 athletic dynamism paired with cloud-like air suspension.',
      rating: 5.0,
      reviewsCount: 94,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Mercedes-Benz',
      model: 'C-Class',
      variant: 'C 300 AMG Line',
      type: 'car',
      category: 'Luxury',
      seatingCapacity: 5,
      doors: 4,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      drivetrain: 'Rear-Wheel Drive',
      engine: { displacementCC: 1999, powerBHP: 255, torqueNm: 400 },
      rental: { pricePerHour: 550, pricePerDay: 8500, pricePerWeek: 52000, refundableDeposit: 18000 },
      location: getLoc('Mumbai')._id,
      cityName: 'Mumbai',
      availableCities: ['Mumbai', 'Pune', 'Goa', 'Delhi', 'Raipur'],
      coordinates: { type: 'Point', coordinates: [72.8697, 19.0657] },
      specifications: { acceleration: '0-100 in 5.9s', topSpeed: '246 km/h', mileage: '14.5 km/l', luggageCapacity: '455 Litres', fuelTankCapacity: '66 Litres' },
      features: ['MBUX Portrait Touchscreen', 'Burmester 3D Surround Sound (15 Speakers)', '64-Color Ambient Lighting with Air Vent Illumination', 'AMG Body Styling', 'Digital Light with Projection'],
      images: [{ url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1000&q=80', alt: 'Mercedes-Benz C-Class' }],
      colorOptions: [{ name: 'Obsidian Black', hex: '#0b0c0e' }, { name: 'Polar White', hex: '#ffffff' }, { name: 'Selenite Grey', hex: '#44484e' }],
      description: 'Often called the Baby S-Class. Ultra-plush executive craftsmanship, portrait touchscreen, and unmatched prestige.',
      rating: 4.9,
      reviewsCount: 118,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Porsche',
      model: '911',
      variant: 'Carrera S Cabriolet',
      type: 'car',
      category: 'Convertible',
      seatingCapacity: 2,
      doors: 2,
      fuelType: 'Petrol',
      transmission: 'Automatic',
      drivetrain: 'Rear-Wheel Drive (PDK)',
      engine: { displacementCC: 2981, powerBHP: 444, torqueNm: 530 },
      rental: { pricePerHour: 1500, pricePerDay: 22000, pricePerWeek: 130000, refundableDeposit: 50000 },
      location: getLoc('Goa')._id,
      cityName: 'Goa',
      availableCities: ['Goa', 'Mumbai', 'Delhi', 'Bengaluru'],
      coordinates: { type: 'Point', coordinates: [73.8180, 15.4868] },
      specifications: { acceleration: '0-100 in 3.7s', topSpeed: '306 km/h', mileage: '9.2 km/l', luggageCapacity: '132 Litres', fuelTankCapacity: '64 Litres' },
      features: ['Twin-Turbo Flat-Six Engine', 'Sport Chrono Package with Mode Switch', 'Open-Top Convertible Soft Top (12s)', 'Sport Exhaust with Active Flaps', 'Porsche Active Suspension Management (PASM)'],
      images: [{ url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=80', alt: 'Porsche 911 Carrera S' }],
      colorOptions: [{ name: 'Guards Red', hex: '#d11212' }, { name: 'Racing Yellow', hex: '#f0c808' }, { name: 'GT Silver Metallic', hex: '#b5b9bd' }],
      description: 'The timeless German supercar icon. Flat-six engine wail, open-air coastal cruising in Goa, and 0-100 in an explosive 3.7 seconds.',
      rating: 5.0,
      reviewsCount: 45,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },

    // ==========================================
    // 🏍️ BIKES & SUPERBIKES (INDIA-FIRST)
    // ==========================================
    {
      brand: 'Royal Enfield',
      model: 'Classic 350',
      variant: 'Dark Stealth Black',
      type: 'bike',
      category: 'Cruiser',
      seatingCapacity: 2,
      doors: 0,
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'Chain Drive',
      engine: { displacementCC: 349, powerBHP: 20, torqueNm: 27 },
      rental: { pricePerHour: 80, pricePerDay: 1100, pricePerWeek: 6800, refundableDeposit: 2500 },
      location: getLoc('Bhilai')._id,
      cityName: 'Bhilai',
      availableCities: ['Bhilai', 'Raipur', 'Durg', 'Nagpur', 'Goa'],
      coordinates: { type: 'Point', coordinates: [81.3629, 21.2121] },
      specifications: { acceleration: '0-60 in 5.1s', topSpeed: '115 km/h', mileage: '36.2 km/l', fuelTankCapacity: '13 Litres', curbWeight: '195 kg' },
      features: ['J-Series Smooth Counterbalanced Engine', 'Dual-Channel ABS', 'Tripper Navigation Pod', 'Classic Thump Exhaust Note', 'Alloy Wheels with Tubeless Tyres'],
      images: [{ url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1000&q=80', alt: 'Royal Enfield Classic 350' }],
      colorOptions: [{ name: 'Stealth Black Matte', hex: '#1c1c1f' }, { name: 'Halcyon Green', hex: '#18382b' }, { name: 'Gunmetal Grey', hex: '#4a4d52' }],
      description: "The soul of Indian motorcycling. Iconic low-end thump, relaxed upright touring posture, and timeless British heritage.",
      rating: 4.9,
      reviewsCount: 310,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Royal Enfield',
      model: 'Himalayan 450',
      variant: 'Hanle Black Tubeless',
      type: 'bike',
      category: 'Adventure',
      seatingCapacity: 2,
      doors: 0,
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'Chain Drive',
      engine: { displacementCC: 452, powerBHP: 40, torqueNm: 40 },
      rental: { pricePerHour: 120, pricePerDay: 1700, pricePerWeek: 10500, refundableDeposit: 4000 },
      location: getLoc('Raipur')._id,
      cityName: 'Raipur',
      availableCities: ['Raipur', 'Bhilai', 'Delhi', 'Goa', 'Bengaluru'],
      coordinates: { type: 'Point', coordinates: [81.6296, 21.2514] },
      specifications: { acceleration: '0-100 in 6.4s', topSpeed: '152 km/h', mileage: '30.0 km/l', fuelTankCapacity: '17 Litres', curbWeight: '196 kg' },
      features: ['Sherpa 450 Liquid-Cooled DOHC Engine', 'Full-Map Google Navigation on Circular TFT', 'Long-Travel 200mm Showa Suspension', 'Switchable Rear ABS for Dirt Trails', 'Ride-by-Wire with Eco/Performance Modes'],
      images: [{ url: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1000&q=80', alt: 'Royal Enfield Himalayan 450' }],
      colorOptions: [{ name: 'Hanle Black Gold', hex: '#151515' }, { name: 'Kaza Brown', hex: '#524335' }, { name: 'Kamet White', hex: '#eaeaea' }],
      description: 'Built in the Himalayas to go anywhere on earth. Liquid-cooled 40HP engine, 200mm suspension clearance, and full Google Maps display.',
      rating: 5.0,
      reviewsCount: 140,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Yamaha',
      model: 'MT-15',
      variant: 'V2 Deluxe Dark Matte Blue',
      type: 'bike',
      category: 'Streetfighter',
      seatingCapacity: 2,
      doors: 0,
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'Chain Drive',
      engine: { displacementCC: 155, powerBHP: 18.4, torqueNm: 14.1 },
      rental: { pricePerHour: 70, pricePerDay: 950, pricePerWeek: 5800, refundableDeposit: 2000 },
      location: getLoc('Bhilai')._id,
      cityName: 'Bhilai',
      availableCities: ['Bhilai', 'Raipur', 'Durg', 'Nagpur', 'Pune'],
      coordinates: { type: 'Point', coordinates: [81.3629, 21.2121] },
      specifications: { acceleration: '0-100 in 11.5s', topSpeed: '130 km/h', mileage: '48.0 km/l', fuelTankCapacity: '10 Litres', curbWeight: '141 kg' },
      features: ['Variable Valve Actuation (VVA)', 'Inverted Front Golden USD Forks', 'Traction Control System (TCS)', 'Assist & Slipper Clutch', 'Bi-Functional LED Headlight'],
      images: [{ url: 'https://images.unsplash.com/photo-1609630875171-b1321377ee65?auto=format&fit=crop&w=1000&q=80', alt: 'Yamaha MT-15 V2' }],
      colorOptions: [{ name: 'Cyan Storm', hex: '#00d2d3' }, { name: 'Metallic Black', hex: '#111215' }, { name: 'Racing Blue', hex: '#003399' }],
      description: 'Dark Side of Japan. Hyper-agile city streetfighter with MotoGP-derived Deltabox frame, inverted golden forks, and class-leading mileage.',
      rating: 4.8,
      reviewsCount: 175,
      isFeatured: false,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'KTM',
      model: 'Duke 390',
      variant: 'Gen-3 Electronic Package',
      type: 'bike',
      category: 'Streetfighter',
      seatingCapacity: 2,
      doors: 0,
      fuelType: 'Petrol',
      transmission: 'Manual',
      drivetrain: 'Chain Drive',
      engine: { displacementCC: 399, powerBHP: 45.3, torqueNm: 39 },
      rental: { pricePerHour: 140, pricePerDay: 1900, pricePerWeek: 11800, refundableDeposit: 5000 },
      location: getLoc('Pune')._id,
      cityName: 'Pune',
      availableCities: ['Pune', 'Mumbai', 'Goa', 'Bengaluru', 'Delhi'],
      coordinates: { type: 'Point', coordinates: [73.9143, 18.5679] },
      specifications: { acceleration: '0-100 in 5.4s', topSpeed: '170 km/h', mileage: '28.5 km/l', fuelTankCapacity: '15 Litres', curbWeight: '168 kg' },
      features: ['Cornering ABS & Supermoto Mode', 'Quickshifter+ (Bi-Directional Clutchless)', 'Launch Control with 5" TFT Glass Screen', 'Adjustable WP APEX Suspension', 'Ride-by-Wire with 3 Riding Modes (Street/Rain/Track)'],
      images: [{ url: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=1000&q=80', alt: 'KTM Duke 390' }],
      colorOptions: [{ name: 'Electronic Orange', hex: '#ff6600' }, { name: 'Atlantic Blue', hex: '#0a3d62' }],
      description: 'The ultimate pocket rocket. 45 horsepower pure adrenaline, cornering ABS, bi-directional quickshifter, and aggressive Austrian stance.',
      rating: 5.0,
      reviewsCount: 215,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },

    // ==========================================
    // 🛵 SCOOTERS & ELECTRIC MOBILITY (EV)
    // ==========================================
    {
      brand: 'Honda',
      model: 'Activa 6G',
      variant: 'H-Smart Key Edition',
      type: 'scooter',
      category: 'Commuter',
      seatingCapacity: 2,
      doors: 0,
      fuelType: 'Petrol',
      transmission: 'Single-Speed Automatic',
      drivetrain: 'Belt Drive (CVT)',
      engine: { displacementCC: 109.5, powerBHP: 7.7, torqueNm: 8.9 },
      rental: { pricePerHour: 40, pricePerDay: 500, pricePerWeek: 3000, refundableDeposit: 1500 },
      location: getLoc('Bhilai')._id,
      cityName: 'Bhilai',
      availableCities: ['Bhilai', 'Raipur', 'Durg', 'Nagpur', 'Goa', 'Pune'],
      coordinates: { type: 'Point', coordinates: [81.3629, 21.2121] },
      specifications: { acceleration: '0-60 in 9.2s', topSpeed: '85 km/h', mileage: '50.0 km/l', fuelTankCapacity: '5.3 Litres', curbWeight: '106 kg' },
      features: ['Smart Key Remote with Anti-Theft Lock', 'eSP Silent ACG Starter', 'Telescopic Front Suspension', 'External Fuel Filling Lid', 'Combi-Brake System (CBS)'],
      images: [{ url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1000&q=80', alt: 'Honda Activa 6G' }],
      colorOptions: [{ name: 'Decent Blue Metallic', hex: '#16314f' }, { name: 'Pearl Siren Blue', hex: '#0e7090' }, { name: 'Matte Axis Grey', hex: '#404347' }],
      description: "India's highest-selling family scooter. Effortless smooth ride, smart-key entry, whisper-quiet start, and massive 50 km/l fuel efficiency.",
      rating: 4.8,
      reviewsCount: 390,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Ola Electric',
      model: 'S1 Pro',
      variant: 'Gen-2 Hyper Mode 4kWh',
      type: 'ev',
      category: 'Electric',
      seatingCapacity: 2,
      doors: 0,
      fuelType: 'Electric',
      transmission: 'Single-Speed Automatic',
      drivetrain: 'Mid-Drive Electric Motor',
      engine: { displacementCC: 0, powerBHP: 14.7, torqueNm: 58 },
      battery: { capacityKWh: 4.0, rangeKm: 180 },
      rental: { pricePerHour: 50, pricePerDay: 750, pricePerWeek: 4500, refundableDeposit: 2000 },
      location: getLoc('Bengaluru')._id,
      cityName: 'Bengaluru',
      availableCities: ['Bengaluru', 'Hyderabad', 'Pune', 'Mumbai', 'Raipur'],
      coordinates: { type: 'Point', coordinates: [77.6412, 12.9784] },
      specifications: { acceleration: '0-40 in 2.6s (Hyper Mode)', topSpeed: '120 km/h', mileage: '180 km / charge', curbWeight: '116 kg' },
      features: ['MoveOS 4 Touchscreen with GPS Map Navigation', 'Cruise Control & Party Mode Music', 'Hyper Mode with 58Nm Instant Torque', 'Reverse Mode for Easy Parking', 'Keyless Phone Bluetooth Unlock'],
      images: [{ url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1000&q=80', alt: 'Ola S1 Pro Gen 2' }],
      colorOptions: [{ name: 'Stellar Blue', hex: '#1b4f72' }, { name: 'Midnight Black', hex: '#111215' }, { name: 'Amethyst Red', hex: '#78281f' }],
      description: 'High-tech EV scooter sensation. 180 km real-world range, explosive 2.6s acceleration in Hyper mode, onboard stereo speakers, and zero fuel expenses.',
      rating: 4.9,
      reviewsCount: 165,
      isFeatured: true,
      availabilityStatus: 'available',
      active: true
    },
    {
      brand: 'Ather',
      model: '450X',
      variant: 'Gen-3.1 Warp Plus Edition',
      type: 'ev',
      category: 'Electric',
      seatingCapacity: 2,
      doors: 0,
      fuelType: 'Electric',
      transmission: 'Single-Speed Automatic',
      drivetrain: 'Belt-Driven Permanent Magnet Motor',
      engine: { displacementCC: 0, powerBHP: 8.6, torqueNm: 26 },
      battery: { capacityKWh: 3.7, rangeKm: 150 },
      rental: { pricePerHour: 50, pricePerDay: 700, pricePerWeek: 4200, refundableDeposit: 2000 },
      location: getLoc('Hyderabad')._id,
      cityName: 'Hyderabad',
      availableCities: ['Hyderabad', 'Bengaluru', 'Pune', 'Mumbai', 'Raipur'],
      coordinates: { type: 'Point', coordinates: [78.3807, 17.4483] },
      specifications: { acceleration: '0-40 in 3.3s (Warp Mode)', topSpeed: '90 km/h', mileage: '150 km / charge', curbWeight: '111 kg' },
      features: ['Ather Grid Fast-Charging (1.5 km/min)', '7" Snapdragon Water-Resistant Touchscreen', 'Google Maps On-Screen Navigation', 'AutoHold Hill Assist (No roll-back)', 'Warp Mode Throttle Response'],
      images: [{ url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?auto=format&fit=crop&w=1000&q=80', alt: 'Ather 450X' }],
      colorOptions: [{ name: 'Space Grey with Neon Accents', hex: '#2c3e50' }, { name: 'Cosmic Black', hex: '#0f1012' }, { name: 'Salt Green', hex: '#638b7e' }],
      description: 'The precision engineering benchmark for electric two-wheelers. Aluminum chassis, AutoHold hill assist, and razor-sharp handling.',
      rating: 5.0,
      reviewsCount: 120,
      isFeatured: false,
      availabilityStatus: 'available',
      active: true
    }
  ];
}
